### PR TITLE
Add grand prix endpoints, fix validations

### PR DESCRIPTION
**Pull request by Mario-659**
1. We were missing validation of not null on object property. After POST with body with track but without trackname:
```json
{
    "grandPrix": "Azerbaijan Grand Prix",
    "track": {
        
    },
    "date": "2022-06-12"
}
```
this is what we were getting (message is from JPA):
```json
{
    "message": "The given id must not be null!; nested exception is java.lang.IllegalArgumentException: The given id must not be null!"
}
```
I didn't find a way to validate this using javax.validation (you can use @NotNull on getter but we are using lombok), so I'm asserting this in service. I also added missing validations in *TeamService* and *PartService*

2. Fixed assertion names in services

### CODE REVIEW

**Comment by lukaszmichalskii** [comment]
`existsById()` method return `true` whether an entity with the given id exists, so this and other ifs work as described previously. I think I messed up with this assert prefix in the method and misunderstood your intentions when created. I used to write such helpers in a different manner. Tested in Postman + PUT task test coverage in Accidents.

**Review by lukaszmichalskii — APPROVED** [review]

**Comment by lukaszmichalskii** [comment]
Before merge, consider DELETE and PUT requests handling and give feedback on why it was skipped

**Comment by Mario-659** [comment]
I didn't add this because for some reason (or no reason at all) I didn't add DELETE and PUT when designing controllers in #13. Now I tried to add DELETE and it seems to be problematic as we have `GrandPrix` in `SeasonResult`. After removing entity I got this:
```
org.postgresql.util.PSQLException: ERROR: update or delete on table "grand_prix" violates foreign key constraint "fkpcwn25udxstb6pxttur2yrtk6" on table "season_result"
```
We won't have this problem with PUT so I will add that.

I can see two solutions for that DELETE:
1. We are skipping DELETE for this controller.
2. After DELETE every SeasonResult with given GrandPrix is removed

I like the first solution better. What do you think?

**Comment by lukaszmichalskii** [comment]
Ok, it is not crucial feature from user point of view, let's skip it.

**Comment by Mario-659** [comment]
Added POST, tested in Postman

**Review by lukaszmichalskii — APPROVED** [review]
If this is all for this feature feel free to merge. I assume we can live without DELETE

**Pull request merged**
